version: 2
ethernets:
  eth0:
    set-name: eth0
    dhcp4: true
    match:
      macaddress: '${mgmt_mac}'
%{ for name, mac in switch_ports ~}
  ${name}:
    set-name: '${name}'
    dhcp4: false
    match:
      macaddress: '${mac}'
%{ endfor ~}
%{ if switch_ports != {} ~}
vrfs:
  vrf-main:
    table: 1000
    interfaces: ${jsonencode([for name, _ in switch_ports: name])}
%{ endif ~}