#cloud-config
chpasswd:
  expire: false
  users:
  - {name: root, password: root, type: text}
  - {name: "${user}", password: "${user}", type: text}
users:
  - name: "${user}"
    groups: [adm, plugdev, sudo]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - "${ssh_authorized_key}"
package_update: true
%{ if switch_ports != {} ~}
bootcmd:
- netplan apply
- ip address add ${router_id}/32 dev vrf-main
- sysctl -w net.ipv4.ip_forward=1
- sysctl -w net.ipv6.conf.default.forwarding=1
- sysctl -w net.ipv6.conf.all.forwarding=1
packages:
- lldpd
- frr
runcmd:
- systemctl enable --now lldpd.service
- sed -i -e 's/^bgpd=no/bgpd=yes/' -e 's/^bfdd=no/bfdd=yes/' -e 's/^#frr_profile="datacenter"/frr_profile="datacenter"/' /etc/frr/daemons
- systemctl restart frr.service
write_files:
- content: |
    net.ipv4.ip_forward=1
    net.ipv6.conf.default.forwarding=1
    net.ipv6.conf.all.forwarding=1
  path: /etc/sysctl.d/30-ipforward.conf
- content: |
    log syslog informational
    route-map REDISTRIBUTE permit 10
      match interface vrf-main
    router bgp ${bgp_as} vrf vrf-main
      bgp router-id ${router_id}
      bgp bestpath as-path multipath-relax
      neighbor fabric peer-group
      neighbor fabric remote-as external
      neighbor fabric bfd
      %{~ for name, _ in switch_ports ~}
      neighbor ${name} interface peer-group fabric
      %{~ endfor ~}
      address-family ipv4 unicast
        neighbor fabric activate
        redistribute connected route-map REDISTRIBUTE
      exit-address-family
  path: /etc/frr/frr.conf
%{ endif ~}
